// Generates src/lib/version.ts with build info — run before each build
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const EMOJIS = [
  '🧠','⚡','🔮','🎯','🚀','🛰️','📡','🔬','🎧','🔌',
  '📟','🔋','💡','🧿','🧩','🎛️','🎚️','🕹️','🧬','🔭',
  '🌌','🌀','💫','✨','🔥','⚙️','🧰','📊','📈','🔔',
  '🎵','🎶','🧘','🧙','🤖','👾','🦾','🦿','👁️','🧿',
  '🏔️','🌊','🔱','🧬','🦠','🌐','💻','🖥️','⌨️','🖱️',
];

function pickEmojis(seed, count) {
  const result = [];
  let s = seed;
  for (let i = 0; i < count; i++) {
    s = (s * 1103515245 + 12345) & 0x7fffffff;
    result.push(EMOJIS[s % EMOJIS.length]);
  }
  return result;
}

const now = new Date();
const dateStr = now.toISOString().slice(0, 19).replace('T', ' ');
const timestamp = Math.floor(now.getTime() / 1000);
const emojis = pickEmojis(timestamp, 3);

const pkgPath = path.join(__dirname, '..', 'package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
const version = pkg.version || '1.0.0';

const content = `// Auto-generated by scripts/generate-version.js — DO NOT EDIT
export const BUILD_VERSION = '${version}';
export const BUILD_DATE = '${dateStr}';
export const BUILD_EMOJIS = '${emojis.join('')}';
export const BUILD_TS = ${timestamp};
`;

const outPath = path.join(__dirname, '..', 'src', 'lib', 'version.ts');
fs.writeFileSync(outPath, content, 'utf-8');
console.log(`version.ts: v${version} | ${dateStr} | ${emojis.join('')}`);
